@PoliMarketApp.API_HostAddress = https://localhost:7276

###

GET {{PoliMarketApp.API_HostAddress}}/api/humanresources/authorized-vendors

###

GET {{PoliMarketApp.API_HostAddress}}/api/delivery/orders/pending

###

GET {{PoliMarketApp.API_HostAddress}}/api/delivery/orders/pending

###
